version: '3.1'

services:
  mongo:
    image: mongo
    container_name: clients_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: clients_usr
      MONGO_INITDB_ROOT_PASSWORD: clients_pwd
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge