version: '3.1'

services:
  mongo:
    image: mongo
    container_name: clients_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: clients_usr
      MONGO_INITDB_ROOT_PASSWORD: clients_pwd
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network

  rabbitmq:
    build: "devops/docker/rabbitmq/"
    container_name: "rabbitmq_clients"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "local"
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  mongo-compose-network:
    driver: bridge