spring:
  data:
    mongodb:
      uri: mongodb://clients_usr:clients_pwd@localhost:27017/admin

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure.include: "*"