spring:
  data:
    mongodb:
      uri: mongodb://clients_usr:clients_pwd@localhost:27017/admin
      auto-index-creation: true

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: local
    username: rabbitmq
    password: rabbitmq

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure.include: "*"

